# Generated by Django 2.2.7 on 2019-11-26 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20191126_1058'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Author',
            new_name='Klient',
        ),
    ]
