# Generated by Django 2.2.7 on 2019-11-26 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_auto_20191126_1108'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('bitkin', models.CharField(help_text='Ведите номер по каталогу Биткина (#456)', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.CharField(help_text='Ведите полное название метериала (медь, серебро, золото..', max_length=200)),
                ('material_short', models.CharField(help_text='Ведите краткое название метериала (Cu, Ag, Au..', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Nominal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nominal', models.CharField(help_text='Ведите номинал (полушка, 5 копеек, 10 рублей..', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Ruler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите имя правителя, генсека, призидента..', max_length=200)),
                ('year_of_rule', models.CharField(help_text='Введите годы правления', max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='bookinstance',
            name='book',
        ),
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.DeleteModel(
            name='BookInstance',
        ),
        migrations.DeleteModel(
            name='Genre',
        ),
        migrations.DeleteModel(
            name='Klient',
        ),
        migrations.DeleteModel(
            name='Language',
        ),
        migrations.AddField(
            model_name='coin',
            name='material',
            field=models.ForeignKey(help_text='Select a material for this coin', null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Material'),
        ),
        migrations.AddField(
            model_name='coin',
            name='nominal',
            field=models.ForeignKey(help_text='Select a nominal for this coin', null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Nominal'),
        ),
        migrations.AddField(
            model_name='coin',
            name='ruler',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Ruler'),
        ),
    ]
