# Generated by Django 2.2.7 on 2019-11-26 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_auto_20191126_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ruler',
            name='year_of_rule',
            field=models.CharField(blank=True, help_text='Введите годы правления', max_length=200),
        ),
    ]
