# Generated by Django 2.2.7 on 2019-11-26 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_auto_20191126_1217'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coin',
            name='title',
        ),
    ]
