# Generated by Django 2.2.7 on 2019-11-26 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_remove_coin_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='MD',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('md', models.CharField(help_text='Ведите монетный двор (ЕМ, АМ, КМ, СПБ..)', max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='coin',
            name='nalichie',
            field=models.CharField(blank=True, help_text='Количество в коллекции', max_length=3),
        ),
        migrations.AlterField(
            model_name='material',
            name='material',
            field=models.CharField(help_text='Ведите полное название метериала (медь, серебро, золото..)', max_length=200),
        ),
        migrations.AlterField(
            model_name='material',
            name='material_short',
            field=models.CharField(help_text='Ведите краткое название метериала (Cu, Ag, Au..)', max_length=200),
        ),
        migrations.AlterField(
            model_name='nominal',
            name='nominal',
            field=models.CharField(help_text='Ведите номинал (полушка, 5 копеек, 10 рублей..)', max_length=200),
        ),
        migrations.AddField(
            model_name='coin',
            name='md',
            field=models.ForeignKey(help_text='Выберете монетный двор', null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.MD'),
        ),
    ]
