# Generated by Django 2.2.7 on 2019-11-26 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_auto_20191126_1233'),
    ]

    operations = [
        migrations.CreateModel(
            name='MCM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mcm', models.CharField(max_length=200)),
            ],
        ),
    ]
