# Generated by Django 2.2.7 on 2019-11-26 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_mcm'),
    ]

    operations = [
        migrations.AddField(
            model_name='coin',
            name='mcm',
            field=models.ForeignKey(help_text='Минцмейстер', null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.MCM'),
        ),
    ]
