# Generated by Django 2.2.7 on 2019-11-26 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_auto_20191126_1311'),
    ]

    operations = [
        migrations.AddField(
            model_name='coin',
            name='year',
            field=models.CharField(default='0000', help_text='Год выпуска', max_length=20),
        ),
        migrations.AlterField(
            model_name='coin',
            name='gyrt',
            field=models.ForeignKey(blank=True, help_text='Гурт', null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Gyrt'),
        ),
        migrations.AlterField(
            model_name='coin',
            name='mcm',
            field=models.ForeignKey(blank=True, help_text='Минцмейстер', null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.MCM'),
        ),
        migrations.AlterField(
            model_name='coin',
            name='md',
            field=models.ForeignKey(blank=True, help_text='Выберете монетный двор', null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.MD'),
        ),
        migrations.AlterField(
            model_name='coin',
            name='redkost',
            field=models.ForeignKey(blank=True, help_text='Редкость', null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Redkost'),
        ),
    ]
