# Generated by Django 2.2.7 on 2019-11-27 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0015_auto_20191126_1322'),
    ]

    operations = [
        migrations.AddField(
            model_name='coin',
            name='note',
            field=models.TextField(blank=True, help_text='Примечания', max_length=1000),
        ),
    ]
