# Generated by Django 2.2.7 on 2019-11-27 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0016_coin_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ruler',
            name='name',
            field=models.CharField(help_text='Введите имя правителя, генсека, призидента..', max_length=200, verbose_name='Имя'),
        ),
    ]
