# Generated by Django 2.2.7 on 2019-11-27 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0017_auto_20191127_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ruler',
            name='year_of_rule',
            field=models.CharField(blank=True, help_text='Введите годы правления', max_length=200, verbose_name='Годы правления'),
        ),
    ]
