# Generated by Django 2.2.7 on 2019-11-28 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0018_auto_20191127_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nominal',
            name='nominal',
            field=models.CharField(help_text='Ведите номинал (полушка, 5 копеек, 10 рублей..)', max_length=200, verbose_name='номинал'),
        ),
    ]
